### ISSUE TITLE
Specify files to include in package

### ISSUE THREAD

**Issue by fabiode** [endenwer/npm-rails#10]
Hey, me again!

I was wondering if there's a way to specify which files I want to be compiled into `npm-dependecies.js` from a specific package. An example is to use **moment.js** and specify which locale file I want to be included. The files are already inside `node_modules/moment/locales`, but I can't see a way to put them into `npm-dependencies.js`.

Thanks!

**Comment by endenwer** [comment]
@fabiode As I know there is no way to do that because packages itself define required dependencies and files and you can't change it unless you edit source code.

**Comment by fabiode** [comment]
@endenwer ok! thanks for enlightening me!
