### ISSUE TITLE
Not able to use npm-rails in rails 3.2 version. is it compatible? 

### ISSUE THREAD

**Issue by rordev-lab** [endenwer/npm-rails#12]
I want to use this gem for rails 3 application. But due to some reason i am still unable to import the packages from node_modules.
Please guide me if i am missing something.
For example:- I was trying to add the npm package https://www.npmjs.com/package/react-sortable-tree
but when i require this by the statement 
`require 'react-sortable-tree''`
or 
`require 'react-sortable-tree/react-sortable-tree''`
 it raise error 404

Thanks in advance..

**Comment by endenwer** [comment]
It does't work this way. The gem can only attach package to `window` object so you can call it like `window.PackageName`, but not all packages can work this way. This gem is very old and I don't maintain it anymore. There are better options like webpacker.
