### ISSUE TITLE
jQuery referred with wrong case

### ISSUE THREAD

**Issue by pupeno** [endenwer/npm-rails#5]
I still cannot figure out why this is happening, but I just installed the latest version of npm-rails and I have an npm_packages that look like this:

``` ruby
# Browserify is required.
# You can install it globally and delete from here.
npm 'browserify', require: false, development: true

# Add some npm packages
npm "jquery.scrollTo"
```

After running rake npm:install, on the browser, I got this error:

npm-dependencies.self-0c41d68….js?body=1:10290 Uncaught TypeError: Cannot set property 'scrollTo' of undefined

That line looks like this:

``` javascript
window.Jquery.scrollTo = require('jquery.scrollTo')
```

so, something is referring to jQuery as Jquery. I have yet to find it, but tmp/npm-rails/bundle.js contains that like:

``` javascript
window.Jquery.scrollTo = require('jquery.scrollTo')
```

**Comment by endenwer** [comment]
You can specify build_name. Try this:

``` ruby
npm "jquery.scrollTo", build_name: '$.scrollTo'
```

**Comment by pupeno** [comment]
Why is this necessary? Is this library broken?

## 

J. Pablo Fernández pupeno@pupeno.com
http://pupeno.com

**Comment by endenwer** [comment]
By default packages attached to `window` by camelize name, but in some cases need to change the name. For example, if you want `jquery` to be defined as `$` but not `Jquery`.
