### ISSUE TITLE
Lock File

### ISSUE THREAD

**Issue by tomprats** [endenwer/npm-rails#6]
This gem has been really helpful bridging the gap between Rails and NPM. One thing that's missing for me is a lock file similar to how a Gemfile and Gemfile.lock work. I know you can lock the versions, but I think it's still missing an important component for me. Here's how I imagine it working:

rails npm:install

- If npm_packages.lock present
  - install versions from there
- else
  - run rails npm:update

rails npm:update

- install versions from npm_packages or newest and save version numbers to npm_packages.lock

extra

- Could be some logic to ensure all the packages in npm_packages are present in the lock file, otherwise it adds them on rails npm:install

I can take some time to work on it if it sounds like something you agree with and would be interested in having. Thanks for your work on this so far.

**Comment by endenwer** [comment]
Glad to hear that the gem is helpful. 
I think for this task can be used https://docs.npmjs.com/cli/shrinkwrap. This command make a lock file and maybe the gem can use it. I'm not sure if it will be working without package.js.
