### ISSUE TITLE
Multiple Output Files

### ISSUE THREAD

**Issue by tomprats** [endenwer/npm-rails#7]
In a few of my apps I have 2 different javascript files - application and admin. There can be some overlap so I often have a common folder as well. Since they're pretty independent, it would be nice to be able to have 2 or 3 npm_dependency files, or at least output files for including.

Let me know if you're interested. I'm going to do some work and see what I can build this weekend towards these 2 issues. Thanks!

**Comment by endenwer** [comment]
Sounds like a good idea. Maybe it can be done by adding additional parameter to npm_packages. Like `bundle_file`. If it set then bundle dependency to that file instead to npm_dependencies.js by default.

**Comment by tomprats** [comment]
This turned out to be a little too complicated for my tastes
