### ISSUE TITLE
Ignore dependencies for specific package

### ISSUE THREAD

**Issue by fabiode** [endenwer/npm-rails#8]
Hi! Is there a way to ignore dependencies from a specific package?

I will explain why I'm asking this:

I'm using **react-rails** gem to deal with react library, but I would like to use **npm-rails** to deal with other react components, like **react-big-calendar**.

To get `rake npm:install` to work in this case, I had to insert **react** and **react-dom** in the `npm_packages` file, making a duplicate of **react** and **react-dom**, even with `require: false`, the code still is compiled to `npm-dependencies.js`.

What should I do in this case?

Thanks!

**Comment by endenwer** [comment]
HI!
You can use browserify options to ignore packages. I didn't test it but maybe this option will help you `--ignore-missing`.
Config would look like this `config.npm.browserify_option = '--ignore-missing'`.

**Comment by fabiode** [comment]
@endenwer thank you for answering so fast, worked as a charm!

**Comment by fabiode** [comment]
@endenwer I'm sorry, I misthought some things. It worked as I had the react and react-dom modules inside node_modules folder in the project. This way, the `npm:install` could insert the react and react-dom into the `npm-dependencies.js` file. Without the modules, I get the following error:

`Error: Cannot find module 'react' from '/Users/skid/locomotiva/clientes/project/code/project/node_modules/react-big-calendar/lib'`

**Comment by endenwer** [comment]
@fabiode  You can use react from npm and don't include it from react-rails. Like this
```
//= require npm-dependencies
//= require react_ujs
//= require components
```
You can specify required version in the npm_packages file. I think it's the simplest solution.

**Comment by fabiode** [comment]
@endenwer I was trying exactly this, but the `react_ujs_mount.js` keeps raising the following error:

`Uncaught ReferenceError: ReactDOM is not defined`

**Comment by endenwer** [comment]
@fabiode  Add this to npm_packages
```
npm 'react-dom', build_name: 'ReactDOM'
```

**Comment by fabiode** [comment]
@endenwer Smooth! Thank you very much!
