### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by lwjameson** [endenwer/npm-rails#9]
I would love for this to work...

I get this error on rake npm:install

** Invoke npm:install (first_time)
** Execute npm:install
npm install --prefix /Users/Lorin/Work/bmsc --loglevel error alpaca@"latest" 
/Users/Lorin/Work/bmsc
└── alpaca@1.5.22 

/usr/local/bin/browserify  /Users/Lorin/Work/bmsc/tmp/npm-rails/bundle.js > /Users/Lorin/Work/bmsc/vendor/assets/javascripts/npm-rails/development/npm-dependencies.js
Error: Cannot find module 'alpaca' from '/Users/Lorin/Work/bmsc/tmp/npm-rails'
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
rake aborted!
Command failed with status (1): [/usr/local/bin/browserify  /Users/Lorin/Wo...]
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/file_utils.rb:66:in `block in create_shell_runner'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/file_utils.rb:56:in `sh'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/npm-rails-0.2.1/lib/tasks/npm.rake:23:in `block (3 levels) in <top (required)>'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/npm-rails-0.2.1/lib/npm/rails/package_bundler.rb:18:in `bundle'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/npm-rails-0.2.1/lib/npm/rails/package_bundler.rb:7:in `bundle'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/npm-rails-0.2.1/lib/tasks/npm.rake:14:in `block (2 levels) in <top (required)>'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/Users/Lorin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/Lorin/.rbenv/versions/2.3.0/bin/rake:22:in `load'
/Users/Lorin/.rbenv/versions/2.3.0/bin/rake:22:in `<main>'
/Users/Lorin/.rbenv/versions/2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/Lorin/.rbenv/versions/2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => npm:install
r

This is my npm_packages file:

  # Browserify is required.
  # You can install it globally and delete from here. 
  # npm 'browserify', require: false, development: true

  # Add some npm packages

  npm 'alpaca'

I have installed browerify globally

**Comment by endenwer** [comment]
It looks like Alpaca can be installed with this gem because it use gulp and bower to build assets.

**Comment by lwjameson** [comment]
OK.  Thanks for the quick response.
